- name: Import Java Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Install PyMySQL (Python MySQL driver)
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3

- name: Load Schema remotely
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/schema.sql
    login_host: mysql-dev.azdevopsvenkat.site
    login_user: root
    login_password: RoboShop@1

- name: Load app-user Schema remotely
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/app-user.sql
    login_host: mysql-dev.azdevopsvenkat.site
    login_user: root
    login_password: RoboShop@1

- name: Load master-data Schema remotely
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/master-data.sql
    login_host: mysql-dev.azdevopsvenkat.site
    login_user: root
    login_password: RoboShop@1