- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Install Python MySQL dependency (RHEL)
  yum:
    name: python3-PyMySQL
    state: present

- name: Set MySQL root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: RoboShop@1
    login_unix_socket: /var/lib/mysql/mysql.sock
    check_implicit_admin: true
    state: present


#- name: Install Prometheus node exporter
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: prometheus-node-exporter
