- name: Disable NodeJS 16  default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS 20 version
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Import App pre requisites
  ansible.builtin.include_task:
    file: app-prereq.yml

- name: Install NodeJS dependence
  community.general.npm:
    path: /app

- name: Import system-D requisites
  ansible.builtin.include_task:
    file: systemd.yml